### ISSUE TITLE
DOCTYPE

### ISSUE THREAD

**Issue by emhoracek** [positiondev/larceny#20]
It seems like `<!DOCTYPE html>` tags are going missing from the templates when rendered as HTML?

**Comment by patrickt** [comment]
@emhoracek I dug into this and found out this is a known issue with `html-conduit`: https://github.com/snoyberg/xml/issues/43

The upstream `tagstream-conduit` library has no support for doctypes, and (since it was last updated in 2014) appears unlikely to add them. Interestingly enough, `xml-conduit` preserves the doctype correctly: I recorded an example of this [here](https://gist.github.com/patrickt/6b6b98e9a986ac70f5af5e5dbd1de80b).

If we want to define Larceny as an HTML-only library, we could add a function that manually adds a `Doctype` to all of the `Document`s we get back from `html-conduit`. That might be problematic, though, since someone might feed an XML file into Larceny, expecting its doctype to be preserved, only to find that it got replaced by `html`. Alternatively, we could just document that Larceny strips doctypes from templates. What do you think is best?

**Comment by emhoracek** [comment]
Thanks @patrickt. That's very disappointing that the underlying library doesn't support doctypes! They're one of the few really hard requirements of the [html5 spec](https://www.w3.org/TR/html5/syntax.html#the-doctype). If we do allow them to be stripped, then adding `<!DOCTYPE html>` back in seems important.

I definitely wrote this library as if I was only writing it for HTML. In supporting other tagsets, we were mostly thinking of users wanting to support older versions of HTML. Hmm. Now I'm wonder if `Overrides` is currently correct. Maybe it should be using the doctype to figure out what tags are allowed! If you want `blink` and `marquee`, use the HTML 4 doctype. :) There'd still need to be a way to say, "no, I want to write fills for this myself" -- Wayland redefines `address` and another project of ours redefines `a` (sounds weird but it's helpful!). (All this is outside the scope of this issue though)

I think if we were going to support arbitrary XML, then it would be better (maybe necessary?) to parse the given doctypes and figure out the tag sets that way. But HTML5 is not XML at all, and I think it's the most common use case. I'm okay with saying Larceny is only for HTML, maybe even only HTML5.

So, perhaps for now, let it get stripped, and prepend `<!DOCTYPE html>` to the output? And I'll make it clear in the description that Larceny is for HTML templating.

**Comment by patrickt** [comment]
Roger that. Will have a PR in the next few days that prepends an `html` doctype to all output and takes care of adjusting the test cases appropriately.

**Comment by emhoracek** [comment]
I'm going to try appending a `<!DOCTYPE html>` at the point of rendering.

**Comment by emhoracek** [comment]
OKAY so I tried https://github.com/positiondev/larceny/issues/20#issuecomment-284842608 but it's like, when is "the point of rendering"? `render "foo.tpl"` might not have a doctype tag itself -- it may apply a base template of some sort -- and that template may apply another. How does Larceny know when it's found where the doctype declaration goes?

I think instead I want Larceny to provide a special Substitution, `<doctype />`, which gets filled in with the actual HTML doctype. Not the perfect solution maybe but I think it'll work!!

**Comment by emhoracek** [comment]
OH! or maybe the template author doesn't have to worry about it, if Larceny takes care of it -- before feeding into html-conduit, look and see if first tag is doctype. If it's the doctype, insert our fake doctype and proceed to parse. Then the Larceny renderer swaps the correct doctype back in at process time. 😂 what a mess i ❤️  💻  :sob:
